apiVersion: apps/v1
kind: Deployment
metadata:
  name: etteyy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etteyy
  template:
    metadata:
      labels:
        app: etteyy
    spec:
      containers:
      - image: okteto.dev/etteyy:latest
        name: etteyy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "18605670-08f6-11ed-861d-0242ac120002"
        - name: Vless_Path
          value: "/vldd555"
        - name: Vmess_UUID
          value: "18605670-08f6-11ed-861d-0242ac120002"
        - name: Vmess_Path
          value: "/vm6ffs66"
        - name: Share_Path
          value: "/v2link"
